### ISSUE TITLE
Baza MySQL

### ISSUE THREAD

**Issue by m4r3x** [m4r3x/zlota-raczka#1]
Hejo
Wgralem drobna poprawke zebym nie musial stawiac osobnego hosta pod baze. Chcialbym przegladnac jak to wyglada tam w srodku co ewentualnie mozna ulepszyc, z tym ze nie wiem co z baza.

Udalo sie ja odzyskac @krzysztof-niesyto ?

Jakby co to wgraj ja jakos do repo zebym mogl sobie ja przemigrowac ;) Dzieki!

**Comment by krzysztof-niesyto** [comment]
Cześć,

Już na forum pisałem, że udało mi się wszystko odzyskać (przynajmniej tak mi się wydaje, bo stary kod działa).

Postaram się wystawić Ci wieczorem dump bazy (jak zapomnę to weź napisz do mnie jeszcze raz w ramach przypomnienia).

**Comment by m4r3x** [comment]
Oki. Dzięki wielkie 😊 

-----Wiadomość oryginalna-----
Od: "Krzysztof Niesyto" <notifications@github.com>
Wysłano: ‎2015-‎04-‎16 08:36
Do: "m4r3x/zlota-raczka" <zlota-raczka@noreply.github.com>
DW: "Marek Szymeczko" <szymeczkomarek@gmail.com>
Temat: Re: [zlota-raczka] Baza MySQL (#1)

Cześć,
Już na forum pisałem, że udało mi się wszystko odzyskać (przynajmniej tak mi się wydaje, bo stary kod działa).
Postaram się wystawić Ci wieczorem dump bazy (jak zapomnę to weź napisz do mnie jeszcze raz w ramach przypomnienia).

**Comment by krzysztof-niesyto** [comment]
Dodałem do głównego katalogu
