### ISSUE TITLE
Update do PHP 5.5 (clean deprecated code)

### ISSUE THREAD

**Issue by m4r3x** [m4r3x/zlota-raczka#2]
Jw w temacie. Zajme sie tym na dniach, póki co zająłem się indexem.
![ex](https://cloud.githubusercontent.com/assets/3802310/7191378/50911a4c-e48d-11e4-8f40-606ac45db3d7.png)

Zostają jeszcze rejestracje, logowania i prawdopodobnie panel admina.

Apropo #1 

Wszystko działa OK - jednak mam pytanie, tak żeby nie marnować czasu na przeszukiwanie kodu i zgadywanie. @krzysztof-niesyto Jak najlepiej zalogować się do Admina?

Zauważyłem że jest user 'ijo' ale hasło jest zahashowane i nijako się tam bez kombinowania nie dostanę ;)

PS. @krzysztof-niesyto Dawno nie widziałem niczego na czystym PHP, ale to szybko śmiga ^^

**Comment by krzysztof-niesyto** [comment]
Pisałem już dawno na forum, że: ijo / tester

Kod jest stary, był już stary jak zaczynaliśmy robić rączke, dopisałem tylko to co było potrzebne i już. Ale cieszę się, że Ci się podoba ;)

PS. Jakbyś miał jeszcze jakieś pytania to pisz.

**Comment by m4r3x** [comment]
Przeglądałem forum ale widocznie jakoś nie przyuważyłem 😉

Jasne, będę pytał.
